### PR TITLE
Proposition of fixing issue #2, works for me

### PR DESCRIPTION
**Pull request by viciu**

### CODE REVIEW

**Comment by ericrasmussen** [comment]
Thanks for sending this over. I need to think through the consequences a bit more. My first thought is there might be some unintended side effects to quoting all of the values in the payload (if they can be quoted). This library is meant to be a very light wrapper that blindly passes on the values you give it. It more or less requires an auxiliary subscribe function in your application/script, and it makes the most sense to me to quote the email in your app and pass in the quoted value to the payload dict. I'd really like to keep the choices this wrapper makes for you to a minimum. What do you think? I'm open to other ideas here.

**Comment by viciu** [comment]
Ok, I'll try to implement this in some other way for my needs. However please consider: the response from Mailchimp might be misleading, have you seen example error message from #2? It looks like postmonkey has silently swallowed "+" ;)  I checked other lib (mailchimp.chimpy) and there's no problem like that. I can subscribe an email with '+'. I think they quote. If you don't want to quote by default, maybe quoting could be optional in postmonkey? Or quoting function might be passed somehow to the constructor?

**Comment by ericrasmussen** [comment]
OK, I took another look at this and it is definitely something that needs to be addressed in PostMonkey. It looks like the best option might be quoting the entire json string instead of individual values. If I pass in the payload as urllib.quote(payload), everything works fine. For some strange reason they seem to be url decoding the json data before parsing it, which is bizarre and unlike any API I've ever worked with. 

I'm going to confirm this with the MailChimp team if possible and then make the update. Thanks again.

**Comment by ericrasmussen** [comment]
OK, after further research it looks like mailchimp expects the entire json string to be "URL encoded", which in python terms means using urllib.quote(json.dumps(params)). I added it in, updated the tests, and released to pypi. If you run into any other issues with it please let me know.

**Comment by viciu** [comment]
Thanks! I've been testing it for a couple of days and seems to be working now fine.

**Pull request closed without merging**
